# Generated by Django 5.2.5 on 2025-08-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
