# Generated by Django 5.2.5 on 2025-08-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticle', '0002_alter_newsarticlepage_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlepage',
            name='publication_date',
            field=models.DateField(db_index=True),
        ),
    ]
