# Generated by Django 5.2.5 on 2025-08-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsArticle', '0003_alter_newsarticlepage_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticlepage',
            options={'ordering': ['-publication_date']},
        ),
    ]
